spring.application.name=schoolmanager
server.port=${PORT:8081}

# --- CẤU HÌNH DATABASE CỦA BẠN (thanhtan) ---
# Đã điền đúng Host, Tên DB, User và Pass
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=thanhtan;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- CẤU HÌNH HIBERNATE ---
# Quan trọng: Đổi thành 'update' để code tự động tạo bảng (Tables) vào database mới của bạn
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.thymeleaf.cache=false