spring.application.name=schoolmanager
server.port=${PORT:8080}

# --- CẤU HÌNH DATABASE CỦA BẠN (ThanhTan) ---
# Đã điền đúng Host, Tên DB, User và Pass
spring.datasource.url=jdbc:sqlserver://den1.mssql8.gear.host;databaseName=thanhtan;encrypt=true;trustServerCertificate=true
spring.datasource.username=thanhtan
spring.datasource.password=Bz8D2_-2Z06a

# --- CẤU HÌNH HIBERNATE ---
# Quan trọng: Đổi thành 'update' để code tự động tạo bảng (Tables) vào database mới của bạn
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.thymeleaf.cache=false